// Screen 10 – Invoice PDF
export function renderInvoice(container, navigate) {
  container.innerHTML = `
  <div class="page-wrap" style="max-width:800px;margin:0 auto;padding:28px 20px;">
    <div class="page-header-row">
      <div>
        <h1 style="font-family:'Syne',sans-serif;font-size:22px;font-weight:800;">🧾 Invoice</h1>
        <p style="color:var(--text-light);font-size:13px;">Auto-generated by PDFKit (Node.js) · Downloadable from Customer Dashboard</p>
      </div>
      <div style="display:flex;gap:10px;">
        <button class="btn btn-ghost btn-sm" onclick="window._nav('customer-dash')">← Dashboard</button>
        <button class="btn btn-accent btn-sm" onclick="window.print()">⬇️ Download PDF</button>
      </div>
    </div>

    <div class="invoice-page">
      <!-- Header -->
      <div class="invoice-header">
        <div>
          <div style="font-family:'Syne',sans-serif;font-size:26px;font-weight:800;color:var(--dark);">
            Chahar Packers
          </div>
          <div style="font-family:'Syne',sans-serif;font-size:26px;font-weight:800;color:var(--accent);margin-top:-6px;">
            &amp; Movers
          </div>
          <div style="font-size:12px;color:var(--text-light);margin-top:8px;line-height:1.7;">
            Shubh Vatika, Millennium Park Road<br>
            Dindoli, Surat, Gujarat – 394210<br>
            📞 +91 9081882281<br>
            ✉️ info@chaharpackersandmovers.com<br>
            GSTIN: 24AABCC1234F1Z5
          </div>
        </div>
        <div style="text-align:right;">
          <div style="font-family:'Syne',sans-serif;font-size:32px;font-weight:800;color:var(--primary);letter-spacing:-1px;">INVOICE</div>
          <div style="font-size:13px;color:var(--text-light);margin-top:10px;line-height:1.8;">
            <strong>Invoice #:</strong> INV-2026-0412<br>
            <strong>Booking ID:</strong> BK-2026-0412<br>
            <strong>Date:</strong> April 28, 2026<br>
            <strong>Due Date:</strong> On Delivery<br>
          </div>
          <span style="display:inline-block;margin-top:12px;padding:6px 20px;background:var(--success);color:#fff;border-radius:8px;font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:1px;">
            ✅ PAID
          </span>
        </div>
      </div>

      <!-- Bill To / From -->
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:24px;margin:24px 0;padding:20px;background:var(--surface);border-radius:10px;">
        <div>
          <div style="font-size:10px;text-transform:uppercase;letter-spacing:.8px;color:var(--text-light);font-weight:700;margin-bottom:8px;">Bill To</div>
          <div style="font-weight:700;font-size:15px;">Rahul Sharma</div>
          <div style="font-size:12.5px;color:var(--text-light);line-height:1.8;margin-top:4px;">
            Flat 4B, Rose Apartments<br>
            Koregaon Park, Pune – 411001<br>
            📞 +91 98765 43210<br>
            ✉️ rahul.sharma@example.com
          </div>
        </div>
        <div>
          <div style="font-size:10px;text-transform:uppercase;letter-spacing:.8px;color:var(--text-light);font-weight:700;margin-bottom:8px;">Service Details</div>
          <div style="font-size:12.5px;line-height:1.8;">
            <strong>Service:</strong> Household Shifting<br>
            <strong>Pickup:</strong> Koregaon Park, Pune<br>
            <strong>Delivery:</strong> Borivali West, Mumbai<br>
            <strong>Date:</strong> April 28, 2026<br>
            <strong>Driver:</strong> Ramesh Kumar · MH-12-AB-4321
          </div>
        </div>
      </div>

      <!-- Items table -->
      <table class="invoice-items">
        <thead>
          <tr>
            <th style="width:40px;">#</th>
            <th>Description</th>
            <th style="width:80px;text-align:right;">Qty</th>
            <th style="width:120px;text-align:right;">Unit Price</th>
            <th style="width:120px;text-align:right;">Amount</th>
          </tr>
        </thead>
        <tbody>
          ${[
            [1, 'Base Fare – Household Shifting',     '1',    '₹2,500',   '₹2,500'],
            [2, 'Distance Charge (320 km × ₹4.5)',    '320 km','₹4.5/km',  '₹1,440'],
            [3, 'Labour Charges (500 kg × ₹2.2)',     '500 kg','₹2.2/kg',  '₹1,100'],
            [4, 'Packing Material',                   '1 set', '₹800',     '₹800'],
            [5, 'Transit Insurance (3% of base fare)', '1',    '₹75',      '₹75'],
          ].map(r => `
            <tr>
              <td style="color:var(--text-light);">${r[0]}</td>
              <td>${r[1]}</td>
              <td style="text-align:right;color:var(--text-light);">${r[2]}</td>
              <td style="text-align:right;color:var(--text-light);">${r[3]}</td>
              <td style="text-align:right;font-weight:600;">${r[4]}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <!-- Totals -->
      <div style="display:flex;justify-content:flex-end;margin-top:8px;">
        <div style="width:320px;">
          ${[
            ['Subtotal',          '₹5,915'],
            ['GST @ 18%',         '₹1,065'],
            ['Discount',          '– ₹180'],
          ].map(([k,v]) => `
            <div style="display:flex;justify-content:space-between;padding:7px 0;border-bottom:1px solid var(--border);font-size:13.5px;">
              <span style="color:var(--text-light);">${k}</span><span>${v}</span>
            </div>
          `).join('')}
          <div style="display:flex;justify-content:space-between;padding:14px 0 4px;font-family:'Syne',sans-serif;font-size:20px;font-weight:800;border-top:2px solid var(--dark);margin-top:6px;">
            <span>Total</span><span style="color:var(--primary);">₹6,800</span>
          </div>
        </div>
      </div>

      <!-- Payment info -->
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:28px;padding-top:20px;border-top:2px dashed var(--border);">
        <div>
          <div style="font-size:11px;text-transform:uppercase;letter-spacing:.7px;color:var(--text-light);font-weight:700;margin-bottom:8px;">Payment Method</div>
          <div style="font-size:13px;line-height:1.8;">
            💳 Paid via UPI<br>
            Transaction ID: UPI-2026-AB-78213<br>
            Date: April 28, 2026 · 6:14 PM
          </div>
        </div>
        <div>
          <div style="font-size:11px;text-transform:uppercase;letter-spacing:.7px;color:var(--text-light);font-weight:700;margin-bottom:8px;">Notes</div>
          <div style="font-size:12.5px;color:var(--text-light);line-height:1.7;">
            Thank you for choosing Chahar Packers &amp; Movers.<br>
            This is a computer-generated invoice.
          </div>
        </div>
      </div>

      <!-- Footer rule -->
      <div style="margin-top:28px;padding-top:16px;border-top:1px solid var(--border);text-align:center;font-size:11.5px;color:var(--text-light);">
        Chahar Packers &amp; Movers · GSTIN: 24AABCC1234F1Z5 · PAN: AABCC1234F · info@chaharpackersandmovers.com
      </div>
    </div>
  </div>
  `;
  window._nav = navigate;
}
